/// Flutter icons CustomIconspt2
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIconspt2
///      fonts:
///       - asset: fonts/CustomIconspt2.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIconspt2 {
  CustomIconspt2._();

  static const _kFontFam = 'CustomIconspt2';
  static const _kFontPkg = null;

  static const IconData weight = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData height = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health_fitness = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health__1_ = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData healthy = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rest = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hydration = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stretching = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData active__1_ = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData revovery_percentage = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData s7mbef1jxq = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image2vector = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hypertrophy = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image2vector__2_ = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
