/// Flutter icons SIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SIcons
///      fonts:
///       - asset: fonts/SIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SIcons {
  SIcons._();

  static const _kFontFam = 'SIcons';
  static const _kFontPkg = null;

  static const IconData image2vector = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hypertrophy = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image2vector__2_ = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image2vector_1 = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image2vector__3_ = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image2vector__2__1 = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
