/// Flutter icons Strength
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Strength
///      fonts:
///       - asset: fonts/Strength.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Strength {
  Strength._();

  static const _kFontFam = 'Strength';
  static const _kFontPkg = null;

  static const IconData strength1 = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData strength2 = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
